const cloudinary = require('cloudinary').v2;
const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Config
cloudinary.config({
    cloud_name: process.env.VITE_CLOUDINARY_CLOUD_NAME,
    api_key: process.env.VITE_CLOUDINARY_API_KEY,
    api_secret: process.env.VITE_CLOUDINARY_API_SECRET
});

const IMAGES_DIR = path.join(__dirname, '../src/assets/images');
const OUTPUT_FILE = path.join(__dirname, '../src/data/imageUrls.js');

async function migrate() {
    console.log('Starting migration...');
    const files = fs.readdirSync(IMAGES_DIR);
    const mapping = {};

    for (const file of files) {
        if (['.jpg', '.jpeg', '.png', '.svg', '.webp'].includes(path.extname(file).toLowerCase())) {
            console.log(`Uploading ${file}...`);
            try {
                const result = await cloudinary.uploader.upload(path.join(IMAGES_DIR, file), {
                    folder: 'norway_project',
                    use_filename: true,
                    unique_filename: false
                });
                mapping[file] = result.secure_url;
                console.log(`✔ Uploaded: ${file}`);
            } catch (error) {
                console.error(`❌ Failed: ${file}`, error.message);
            }
        }
    }

    const content = `// Auto-generated by scripts/migrateImages.js
export const IMAGES = ${JSON.stringify(mapping, null, 4)};
`;

    fs.writeFileSync(OUTPUT_FILE, content);
    console.log(`Migration complete! URLs saved to ${OUTPUT_FILE}`);
}

migrate();
